Models/purchase_order_line.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class purchase_order_line
    {
        [Display(Name = "Chalan#")]
        public int pol_id { get; set; }
        [Display(Name = "PO#")]
        public int Line_No { get; set; }
        [Display(Name = "Quality of Paper")]
        public string Paper_quality { get; set; }
        [Display(Name = "Quantity")]
        public Nullable<int> Quantity { get; set; }
        [Display(Name = "Number of Plys")]
        public string Number_of_ply { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Amount { get; set; }
        [Display(Name = "PO#")]
        public Nullable<int> po_id { get; set; }
        [Display(Name = "PO#")]
        public virtual purchase_order purchase_order { get; set; }
    }
}

Controllers/purchase_orderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Management_System.Models;

namespace Management_System.Controllers
{
    public class purchase_orderController : Controller
    {
        private Management_SystemEntities3 db = new Management_SystemEntities3();

        // GET: purchase_order
        public ActionResult Index(String searchCompany,int SearchPO=0)
        {
            var purchase_order = db.purchase_order.Include(p => p.Tax);
            if(searchCompany != null && searchCompany != "")
                return View(purchase_order.Where(x => x.company_name.Contains(searchCompany)).ToList());
            if(SearchPO !=0)
            {
                return View(purchase_order.Where(x => x.po_id.Equals(SearchPO)).ToList());
            }
            return View(purchase_order.ToList());

        }

        // GET: purchase_order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order purchase_order = db.purchase_order.Find(id);
            if (purchase_order == null)
            {
                return HttpNotFound();
            }
            return View(purchase_order);
        }

        // GET: purchase_order/Create
        public ActionResult Create()
        {
            ViewBag.tax_id = new SelectList(db.Taxes, "tax_id", "tax_id");
            return View();
        }

        // POST: purchase_order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "po_id,company_name,delivery_dat,po_date,tax_id")] purchase_order purchase_order)
        {
            if (ModelState.IsValid)
            {
                db.purchase_order.Add(purchase_order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.tax_id = new SelectList(db.Taxes, "tax_id", "tax_id", purchase_order.tax_id);
            return View(purchase_order);
        }

        // GET: purchase_order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order purchase_order = db.purchase_order.Find(id);
            if (purchase_order == null)
            {
                return HttpNotFound();
            }
            ViewBag.tax_id = new SelectList(db.Taxes, "tax_id", "tax_id", purchase_order.tax_id);
            return View(purchase_order);
        }

        // POST: purchase_order/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "po_id,company_name,delivery_dat,po_date,tax_id")] purchase_order purchase_order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(purchase_order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.tax_id = new SelectList(db.Taxes, "tax_id", "tax_id", purchase_order.tax_id);
            return View(purchase_order);
        }

        // GET: purchase_order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order purchase_order = db.purchase_order.Find(id);
            if (purchase_order == null)
            {
                return HttpNotFound();
            }
            return View(purchase_order);
        }

        // POST: purchase_order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            purchase_order purchase_order = db.purchase_order.Find(id);
            db.purchase_order.Remove(purchase_order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/purchaseorderlineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using Management_System.Models;

namespace Management_System.Controllers
{
    public class purchaseorderlineController : Controller
    {
        private Management_SystemEntities3 db = new Management_SystemEntities3();

        // GET: purchaseorderline
        public ActionResult Index(int? id)
        {
            var purchase_order_line = db.purchase_order_line.Include(p => p.purchase_order);
            purchase_order_line = from Pl in purchase_order_line  where Pl.po_id == id select Pl;
            return View(purchase_order_line.ToList());
        }

        // GET: purchaseorderline/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order_line purchase_order_line = db.purchase_order_line.Find(id);
            if (purchase_order_line == null)
            {
                return HttpNotFound();
            }
            return View(purchase_order_line);
        }

        // GET: purchaseorderline/Create
        public ActionResult Create()
        {
            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id");
            return View();
        }

        // POST: purchaseorderline/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pol_id,Line_No,Paper_quality,Quantity,Number_of_ply,Height,Width,length,Rate,Amount,po_id")] purchase_order_line purchase_order_line)
        {
            if (ModelState.IsValid)
            {
                int? id = purchase_order_line.po_id;
                db.purchase_order_line.Add(purchase_order_line);
                db.SaveChanges();
                return RedirectToAction("In" +
                    "dex",new { id = id });
            }

            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id", purchase_order_line.po_id);
            return View(purchase_order_line);
        }

        // GET: purchaseorderline/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order_line purchase_order_line = db.purchase_order_line.Find(id);
            if (purchase_order_line == null)
            {
                return HttpNotFound();
            }
            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id", purchase_order_line.po_id);
            return View(purchase_order_line);
        }

        // POST: purchaseorderline/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "pol_id,Line_No,Paper_quality,Quantity,Number_of_ply,Height,Width,length,Rate,Amount,po_id")] purchase_order_line purchase_order_line)
        {
            if (ModelState.IsValid)
            {
                db.Entry(purchase_order_line).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = purchase_order_line.po_id });
            }
            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "company_name", purchase_order_line.po_id);
            return View(purchase_order_line);
        }

        // GET: purchaseorderline/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order_line purchase_order_line = db.purchase_order_line.Find(id);
            if (purchase_order_line == null)
            {
                return HttpNotFound();
            }
            return View(purchase_order_line);
        }

        // POST: purchaseorderline/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            purchase_order_line purchase_order_line = db.purchase_order_line.Find(id);
            db.purchase_order_line.Remove(purchase_order_line);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = purchase_order_line.po_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/purchaseorderline/Create.cshtml
@model Management_System.Models.purchase_order_line

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>purchase line</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.po_id, "po_id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("po_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.po_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.pol_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.pol_id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.pol_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Paper_quality, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Paper_quality, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Paper_quality, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Number_of_ply, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Number_of_ply, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Number_of_ply, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.length, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.length, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.length, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to PO", "Index", "purchase_order")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/purchaseorderline/Delete.cshtml
@model Management_System.Models.purchase_order_line

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>purchase_order_line</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Line_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Line_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paper_quality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paper_quality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number_of_ply)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_of_ply)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.purchase_order.company_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchase_order.company_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id = Model.po_id })
        </div>
    }
</div>

Views/purchaseorderline/Details.cshtml
@model Management_System.Models.purchase_order_line

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>purchase_order_line</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Line_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Line_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paper_quality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paper_quality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number_of_ply)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_of_ply)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.purchase_order.company_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchase_order.company_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.pol_id }) |
    @Html.ActionLink("Back to List", "Index",new { id = Model.po_id })
</p>

Views/purchaseorderline/Edit.cshtml
@model Management_System.Models.purchase_order_line

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>purchase_order_line</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.pol_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Line_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Line_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Line_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Paper_quality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Paper_quality, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Paper_quality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number_of_ply, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number_of_ply, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number_of_ply, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.length, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.length, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.length, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.po_id, "po_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("po_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.po_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index",new { id = Model.po_id })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/purchaseorderline/Index.cshtml
@model IEnumerable<Management_System.Models.purchase_order_line>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.po_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paper_quality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number_of_ply)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Width)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.length)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.po_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paper_quality)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number_of_ply)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Width)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.length)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.pol_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.pol_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.pol_id })
        </td>
    </tr>
}

</table>