Models/purchase_order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class purchase_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase_order()
        {
            this.bills = new HashSet<bill>();
            this.purchase_order_line = new HashSet<purchase_order_line>();
        }
        [Display(Name = "Purchase Order Number")]
        public int po_id { get; set; }
        [Display(Name = "Name of Company")]
        public string company_name { get; set; }
        [Display(Name = "Deliver Date")]
        public Nullable<System.DateTime> delivery_dat { get; set; }
        [Display(Name = "Purchase Order Date")]
        public Nullable<System.DateTime> po_date { get; set; }
        [Display(Name = "Tax")]
        public string tax_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order_line> purchase_order_line { get; set; }
        public virtual Tax Tax { get; set; }
    }
}

Controllers/billsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Management_System.Models;

namespace Management_System.Controllers
{
    public class billsController : Controller
    {
        private Management_SystemEntities3 db = new Management_SystemEntities3();

        // GET: bills
        public ActionResult Index(int? id)
        {
            var bills = db.bills.Include(b => b.purchase_order);
            if(id>0)
            {
                bills = from Pl in bills where Pl.po_id == id select Pl;
            }
            return View(bills.ToList());
        }

        // GET: bills/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bill bill = db.bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // GET: bills/Create
        public ActionResult Create()
        {
            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id");
            return View();
        }

        // POST: bills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "bill_id,bill_date,Payment,Amount,po_id")] bill bill)
        {
            if (ModelState.IsValid)
            {
                db.bills.Add(bill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id", bill.po_id);
            return View(bill);
        }

        // GET: bills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bill bill = db.bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id", bill.po_id);
            return View(bill);
        }

        // POST: bills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "bill_id,bill_date,Payment,Amount,po_id")] bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id", bill.po_id);
            return View(bill);
        }

        // GET: bills/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bill bill = db.bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bill bill = db.bills.Find(id);
            db.bills.Remove(bill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/purchase_orderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Management_System.Models;

namespace Management_System.Controllers
{
    public class purchase_orderController : Controller
    {
        private Management_SystemEntities3 db = new Management_SystemEntities3();

        // GET: purchase_order
        public ActionResult Index(String searchCompany,int SearchPO=0)
        {
            var purchase_order = db.purchase_order.Include(p => p.Tax);
            if(searchCompany != null && searchCompany != "")
                return View(purchase_order.Where(x => x.company_name.Contains(searchCompany)).ToList());
            if(SearchPO !=0)
            {
                return View(purchase_order.Where(x => x.po_id.Equals(SearchPO)).ToList());
            }
            return View(purchase_order.ToList());

        }

        // GET: purchase_order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order purchase_order = db.purchase_order.Find(id);
            if (purchase_order == null)
            {
                return HttpNotFound();
            }
            return View(purchase_order);
        }

        // GET: purchase_order/Create
        public ActionResult Create()
        {
            ViewBag.tax_id = new SelectList(db.Taxes, "tax_id", "tax_id");
            return View();
        }

        // POST: purchase_order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "po_id,company_name,delivery_dat,po_date,tax_id")] purchase_order purchase_order)
        {
            if (ModelState.IsValid)
            {
                db.purchase_order.Add(purchase_order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.tax_id = new SelectList(db.Taxes, "tax_id", "tax_id", purchase_order.tax_id);
            return View(purchase_order);
        }

        // GET: purchase_order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order purchase_order = db.purchase_order.Find(id);
            if (purchase_order == null)
            {
                return HttpNotFound();
            }
            ViewBag.tax_id = new SelectList(db.Taxes, "tax_id", "tax_id", purchase_order.tax_id);
            return View(purchase_order);
        }

        // POST: purchase_order/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "po_id,company_name,delivery_dat,po_date,tax_id")] purchase_order purchase_order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(purchase_order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.tax_id = new SelectList(db.Taxes, "tax_id", "tax_id", purchase_order.tax_id);
            return View(purchase_order);
        }

        // GET: purchase_order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order purchase_order = db.purchase_order.Find(id);
            if (purchase_order == null)
            {
                return HttpNotFound();
            }
            return View(purchase_order);
        }

        // POST: purchase_order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            purchase_order purchase_order = db.purchase_order.Find(id);
            db.purchase_order.Remove(purchase_order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/purchaseorderlineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using Management_System.Models;

namespace Management_System.Controllers
{
    public class purchaseorderlineController : Controller
    {
        private Management_SystemEntities3 db = new Management_SystemEntities3();

        // GET: purchaseorderline
        public ActionResult Index(int? id)
        {
            var purchase_order_line = db.purchase_order_line.Include(p => p.purchase_order);
            purchase_order_line = from Pl in purchase_order_line  where Pl.po_id == id select Pl;
            return View(purchase_order_line.ToList());
        }

        // GET: purchaseorderline/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order_line purchase_order_line = db.purchase_order_line.Find(id);
            if (purchase_order_line == null)
            {
                return HttpNotFound();
            }
            return View(purchase_order_line);
        }

        // GET: purchaseorderline/Create
        public ActionResult Create()
        {
            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id");
            return View();
        }

        // POST: purchaseorderline/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pol_id,Line_No,Paper_quality,Quantity,Number_of_ply,Height,Width,length,Rate,Amount,po_id")] purchase_order_line purchase_order_line)
        {
            if (ModelState.IsValid)
            {
                int? id = purchase_order_line.po_id;
                db.purchase_order_line.Add(purchase_order_line);
                db.SaveChanges();
                return RedirectToAction("In" +
                    "dex",new { id = id });
            }

            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id", purchase_order_line.po_id);
            return View(purchase_order_line);
        }

        // GET: purchaseorderline/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order_line purchase_order_line = db.purchase_order_line.Find(id);
            if (purchase_order_line == null)
            {
                return HttpNotFound();
            }
            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "po_id", purchase_order_line.po_id);
            return View(purchase_order_line);
        }

        // POST: purchaseorderline/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "pol_id,Line_No,Paper_quality,Quantity,Number_of_ply,Height,Width,length,Rate,Amount,po_id")] purchase_order_line purchase_order_line)
        {
            if (ModelState.IsValid)
            {
                db.Entry(purchase_order_line).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = purchase_order_line.po_id });
            }
            ViewBag.po_id = new SelectList(db.purchase_order, "po_id", "company_name", purchase_order_line.po_id);
            return View(purchase_order_line);
        }

        // GET: purchaseorderline/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            purchase_order_line purchase_order_line = db.purchase_order_line.Find(id);
            if (purchase_order_line == null)
            {
                return HttpNotFound();
            }
            return View(purchase_order_line);
        }

        // POST: purchaseorderline/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            purchase_order_line purchase_order_line = db.purchase_order_line.Find(id);
            db.purchase_order_line.Remove(purchase_order_line);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = purchase_order_line.po_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/purchase_order/Create.cshtml
@model Management_System.Models.purchase_order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>purchase_order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.company_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.company_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.company_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.delivery_dat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.delivery_dat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.delivery_dat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.po_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.po_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.po_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tax_id, "tax_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("tax_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tax_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/purchase_order/Delete.cshtml
@model Management_System.Models.purchase_order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>purchase_order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.company_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.delivery_dat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.delivery_dat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.po_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.po_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tax.tax_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tax.tax_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/purchase_order/Details.cshtml
@model Management_System.Models.purchase_order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>purchase_order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.company_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.delivery_dat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.delivery_dat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.po_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.po_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tax.tax_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tax.tax_id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.po_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/purchase_order/Edit.cshtml
@model Management_System.Models.purchase_order

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>purchase_order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.po_id)

        <div class="form-group">
            @Html.LabelFor(model => model.company_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.company_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.company_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.delivery_dat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.delivery_dat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.delivery_dat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.po_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.po_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.po_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tax_id, "tax_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("tax_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tax_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/purchase_order/Index.cshtml
@model IEnumerable<Management_System.Models.purchase_order>

@{
    ViewBag.Title = "Index";
}

<h2>Orders Records</h2>

<p>
    @Html.ActionLink("Generate New Order", "Create")
</p>
<p>
    @using (@Html.BeginForm())
    {
        @Html.TextBox("searchCompany") <input type="submit" value="searchCompany" />

        @Html.TextBox("SearchPO") <input type="submit" value="SearchPO" />

    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.po_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.company_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.delivery_dat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.po_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tax.tax_id)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr style="">
    <td>
        @Html.DisplayFor(modelItem => item.po_id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.company_name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.delivery_dat)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.po_date)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Tax.tax_id)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.po_id }) |
        @Html.ActionLink("Details", "Details", new { id = item.po_id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.po_id }) |
        @Html.ActionLink("Material Entry", "Index", "purchaseorderline", new { id = item.po_id }, null)|
        @Html.ActionLink("View Bill", "Index", "bills", new { id = item.po_id }, null)

    </td>
</tr>
}

</table>